### ISSUE TITLE
Any plans to support route matching?

### ISSUE THREAD

**Issue by leomelin** [taitulism/Bootstruct#2]
As I understood, it's currently not possible to use route matching like ````/users/:id```` to create a RESTful API? Also regex matches on routes would be awesome. Any plans to support those with some mechanism?

Edit: Oh, I noticed that params array in e.g. ````GET /users ```` will contain the ````:id```` as the first item. Sorry, didn't notice that first.

**Comment by taitulism** [comment]
np :]

Just 4 the record:
`io.params` is an array that holds the different URL parts: `/a/b` ---> `io.params = ['a','b']`.
if **'a'** is an existing controller/folder but **'b'** isn't, io.params would be = `['b']`.

So the Bootstruct equivalent to `/users/:id` would be:
    1. having a `users` folder
    2. handling `io.params[0]` as `:id`
